"""add user columns

Revision ID: 2e7b8671dbdf
Revises: 910f7e43a2ba
Create Date: 2025-09-04 09:12:13.348992

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e7b8671dbdf"
down_revision: Union[str, Sequence[str], None] = "910f7e43a2ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("idx_users_created_at", "users", ["created_at"], unique=False)
    op.create_index("idx_users_email_active", "users", ["email", "is_active"], unique=False)
    op.create_unique_constraint("uq_users_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_email", "users", type_="unique")
    op.drop_index("idx_users_email_active", table_name="users")
    op.drop_index("idx_users_created_at", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
