"""add_email_management_tables

Revision ID: 4cbc48e9e690
Revises: 20250909_175441
Create Date: 2025-09-10 18:23:04.493023

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cbc48e9e690"
down_revision: Union[str, Sequence[str], None] = "20250909_175441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connected_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("account_email", sa.String(length=255), nullable=False),
        sa.Column("access_token_enc", sa.Text(), nullable=False),
        sa.Column("refresh_token_enc", sa.Text(), nullable=False),
        sa.Column("token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("sync_cursor", sa.String(length=255), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", "account_email", name="uq_user_provider_email"),
    )
    op.create_index(
        "idx_connected_accounts_last_synced", "connected_accounts", ["last_synced_at"], unique=False
    )
    op.create_index(
        "idx_connected_accounts_provider", "connected_accounts", ["provider"], unique=False
    )
    op.create_index(
        "idx_connected_accounts_sync_status", "connected_accounts", ["sync_status"], unique=False
    )
    op.create_index(
        "idx_connected_accounts_user_id", "connected_accounts", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_connected_accounts_id"), "connected_accounts", ["id"], unique=False)
    op.create_table(
        "emails",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("sender", sa.String(length=255), nullable=True),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_storage_key", sa.String(length=255), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("is_flagged", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("ml_processed", sa.Boolean(), nullable=False),
        sa.Column("is_phishing", sa.Boolean(), nullable=True),
        sa.Column("phishing_score", sa.Float(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["connected_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_emails_account_date", "emails", ["account_id", "date"], unique=False)
    op.create_index("idx_emails_account_id", "emails", ["account_id"], unique=False)
    op.create_index("idx_emails_date", "emails", ["date"], unique=False)
    op.create_index("idx_emails_is_flagged", "emails", ["is_flagged"], unique=False)
    op.create_index("idx_emails_is_read", "emails", ["is_read"], unique=False)
    op.create_index("idx_emails_ml_processed", "emails", ["ml_processed"], unique=False)
    op.create_index(
        "idx_emails_provider_message_id", "emails", ["provider_message_id"], unique=False
    )
    op.create_index("idx_emails_sender", "emails", ["sender"], unique=False)
    op.create_index("idx_emails_thread_id", "emails", ["thread_id"], unique=False)
    op.create_index(op.f("ix_emails_id"), "emails", ["id"], unique=False)
    op.create_table(
        "attachments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_attachments_content_type", "attachments", ["content_type"], unique=False)
    op.create_index("idx_attachments_email_id", "attachments", ["email_id"], unique=False)
    op.create_index("idx_attachments_storage_key", "attachments", ["storage_key"], unique=False)
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "verification_codes",
        "attempts",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "verification_codes",
        "used",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "verification_codes",
        "used",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "verification_codes",
        "attempts",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_index("idx_attachments_storage_key", table_name="attachments")
    op.drop_index("idx_attachments_email_id", table_name="attachments")
    op.drop_index("idx_attachments_content_type", table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_emails_id"), table_name="emails")
    op.drop_index("idx_emails_thread_id", table_name="emails")
    op.drop_index("idx_emails_sender", table_name="emails")
    op.drop_index("idx_emails_provider_message_id", table_name="emails")
    op.drop_index("idx_emails_ml_processed", table_name="emails")
    op.drop_index("idx_emails_is_read", table_name="emails")
    op.drop_index("idx_emails_is_flagged", table_name="emails")
    op.drop_index("idx_emails_date", table_name="emails")
    op.drop_index("idx_emails_account_id", table_name="emails")
    op.drop_index("idx_emails_account_date", table_name="emails")
    op.drop_table("emails")
    op.drop_index(op.f("ix_connected_accounts_id"), table_name="connected_accounts")
    op.drop_index("idx_connected_accounts_user_id", table_name="connected_accounts")
    op.drop_index("idx_connected_accounts_sync_status", table_name="connected_accounts")
    op.drop_index("idx_connected_accounts_provider", table_name="connected_accounts")
    op.drop_index("idx_connected_accounts_last_synced", table_name="connected_accounts")
    op.drop_table("connected_accounts")
    # ### end Alembic commands ###
